# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 4232);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20141105223254");
user_pref("browser.startup.homepage_override.mstone", "33.0.3");
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1415687432389");
user_pref("datareporting.policy.firstRunTime", "1415601032389");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3234);
user_pref("datareporting.sessions.current.main", 736);
user_pref("datareporting.sessions.current.sessionRestored", 4238);
user_pref("datareporting.sessions.current.startTime", "1415601030932");
user_pref("datareporting.sessions.current.totalTime", 17);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.0.3");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{1E2593B2-E106-4697-BCE7-A9D30DE05D73}\":{\"descriptor\":\"C:\\\\Program Files\\\\HttpWatch\\\\Firefox\",\"mtime\":1310541311853,\"rdfTime\":1277290800000},\"{BBDA0591-3099-440a-AA10-41764D9DB4DB}\":{\"descriptor\":\"C:\\\\ProgramData\\\\Symantec\\\\Symantec Endpoint Protection\\\\12.1.1101.401.105\\\\Data\\\\IPSFF\",\"mtime\":1411992974792,\"rdfTime\":1411992974786},\"fiddlerhook@fiddler2.com\":{\"descriptor\":\"C:\\\\Program Files\\\\Fiddler2\\\\FiddlerHook\",\"mtime\":1415352699309,\"rdfTime\":1401920304000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1415600354055,\"rdfTime\":1415262897000}}},{\"name\":\"winreg-app-user\",\"addons\":{\"dict@www.youdao.com\":{\"descriptor\":\"C:\\\\Users\\\\pascocai\\\\AppData\\\\Local\\\\Youdao\\\\Dict\\\\Application\\\\stable\\\\extensions\\\\firefox\",\"mtime\":1415349987870,\"rdfTime\":1415349985500}}}]");
user_pref("extensions.lastAppVersion", "33.0.3");
user_pref("extensions.lastPlatformVersion", "33.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20141105223254");
user_pref("gecko.mstone", "33.0.3");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 93701);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1415601031);
user_pref("toolkit.telemetry.previousBuildID", "20141105223254");
